module: BluetoothLinux
author: PureSwift
github_url: https://github.com/PureSwift/BluetoothLinux

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, BluetoothLinux.xcodeproj, -target, BluetoothLinux, LIBRARY_SEARCH_PATHS=.build/debug]

